[package]
name = "shallow_red_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = ">0.0.1"
itertools = "0.10.5"
parking_lot = "0.12.1"
serde = { version = "1.0", features = ["derive"] } # needed for the tauri frontend
